// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qifwdnkiidbrjyctugod.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFpZndkbmtpaWRicmp5Y3R1Z29kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE2MDc1MDYsImV4cCI6MjA1NzE4MzUwNn0.x3WUDg5iXtHUa_pJSBUb8_AVDBqFAEwGBn4s9L4AYZY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);